BUG-FIX --- Comment: Fixed the function register() in the class Auth. Use of user.profile.save() before user.save() to register a new user/profile.
Plattform:
Linux L3F591407.INNOQ.com 2.6.35.11-83.fc14.i686 #1 SMP Mon Feb 7 07:04:18 UTC 2011 i686 i686 i386 GNU/Linux

Vendor:
Fedora 14

JDK:
java version "1.6.0_20" (OpenJDK)

Trace:

@65nj2216a

Internal Server Error (500) for request POST /auth/signup

Execution exception (In /app/controllers/Auth.java around line 98)
IllegalStateException occured : org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: models.User.profile -> models.Profile

play.exceptions.JavaExecutionException: org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: models.User.profile -> models.Profile
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:285)
	at Invocation.HTTP Request(Play!)
Caused by: java.lang.IllegalStateException: org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: models.User.profile -> models.Profile
	at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1232)
	at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1168)
	at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1174)
	at org.hibernate.ejb.AbstractEntityManagerImpl.flush(AbstractEntityManagerImpl.java:794)
	at play.db.jpa.JPABase._save(JPABase.java:47)
	at play.db.jpa.GenericModel.save(GenericModel.java:172)
	at controllers.Auth.register(Auth.java:98)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:408)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:403)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:176)
	... 1 more
Caused by: org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: models.User.profile -> models.Profile
	at org.hibernate.engine.CascadingAction$9.noCascade(CascadingAction.java:387)
	at org.hibernate.engine.Cascade.cascade(Cascade.java:172)
	at org.hibernate.event.def.AbstractFlushingEventListener.cascadeOnFlush(AbstractFlushingEventListener.java:154)
	at org.hibernate.event.def.AbstractFlushingEventListener.prepareEntityFlushes(AbstractFlushingEventListener.java:145)
	at org.hibernate.event.def.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener.java:88)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:50)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1206)
	at org.hibernate.ejb.AbstractEntityManagerImpl.flush(AbstractEntityManagerImpl.java:791)
	... 7 more