BUG-FIX --- Comment: This is the second system (Linux) for running the project. The first system (Windows Vista) running the project didn't detect the error. Fixed the function from render() to render("auth/logout.html") in the class Auth.
Plattform:
Linux L3F591407.INNOQ.com 2.6.35.11-83.fc14.i686 #1 SMP Mon Feb 7 07:04:18 UTC 2011 i686 i686 i386 GNU/Linux

Vendor:
Fedora 14

JDK:
java version "1.6.0_20" (OpenJDK)

Trace:

16:09:11,267 ERROR ~

@65mng6a6j
Internal Server Error (500) for request GET /auth/logout

Template not found (In /app/controllers/Auth.java around line 76)
The template Auth/logout.html does not exist.

play.exceptions.TemplateNotFoundException: Template not found : Auth/logout.html
	at play.mvc.Controller.renderTemplate(Controller.java:595)
	at play.mvc.Controller.renderTemplate(Controller.java:568)
	at play.mvc.Controller.render(Controller.java:623)
	at controllers.Auth.logout(Auth.java:76)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:408)
	at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:403)
	at play.mvc.ActionInvoker.invoke(ActionInvoker.java:176)
	at Invocation.HTTP Request(Play!)